Control Daemon management and logging improved

diff --git a/daemon/daemon b/daemon/daemon
--- a/daemon/daemon
+++ b/daemon/daemon
@@ -16,8 +16,8 @@ PATH=$PATH.":REPLACEBYBASEFOLDER/sbin"
 
 ### END INIT INFO
 
-# Version 1.3
-# 31.10.2016 22:10:57
+# Version 1.4
+# 31.10.2016 23:01:51
 
 logfile=REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/knxd.log
 flagfile=REPLACEBYBASEFOLDER/config/plugins/REPLACEBYSUBFOLDER/modify.me
@@ -33,17 +33,27 @@ then
   cd REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/                                                                                             2>&1 >>$logfile
   dpkg -i libpthsem*.deb                                                                                                                              2>&1 >>$logfile
   dpkg -i knxd_*.deb knxd-tools_*.deb                                                                                                                 2>&1 >>$logfile
+  cd                                                                                                                                                  2>&1 >>$logfile
   KNXD_OPTS="`grep KNXD_OPTS $configfile`"                                                                                                            2>&1 >>$logfile
   echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
   sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE                                                                                                    2>&1 >>$logfile
   ln -s REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/eibtime.pl REPLACEBYBASEFOLDER2/system/cron/cron.01min/REPLACEBYPLUGINNAME 2>&1 >>$logfile
+  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
+  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
+	if [ -z "$CS_PID" ]
+	then
+    echo "Process not found, no need to kill it"                                                                                                      2>&1 >>$logfile
+  else
+    echo "Process ID $CS_PID found, killing it"                                                                                                       2>&1 >>$logfile
+    kill -15 $CS_PID                                                                                                                                  2>&1 >>$logfile
+  fi
   echo "Try to start KNXd Control Daemon"                                                                                                             2>&1 >>$logfile
   REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/server_control.pl                                                                2>&1 >>$logfile &
   if [ $? -eq 0 ]
   then
-    echo "KNXd Control Daemon successfully started"                                                                                                   2>&1 >>$logfile
+    echo "KNXd Control Daemon restart successfully completed."                                                                                        2>&1 >>$logfile
   else
-    echo "KNXd Control Daemon start failed"                                                                                                           2>&1 >>$logfile
+    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                      2>&1 >>$logfile
   fi
   echo "Try to read KNXd Version"                                                                                                                     2>&1 >>$logfile
   /usr/bin/knxd -V                                                                                                                                    2>&1 >>$logfile
@@ -71,8 +81,23 @@ else
   KNXD_OPTS="`grep KNXD_OPTS $configfile`"
   echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
   sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE
+  echo "Check, if KNXd Control Daemon is running"                                                                                                     2>&1 >>$logfile
+  CS_PID=`ps -ef|grep "knxd/bin/server_control.pl"|grep -v grep |awk -F" " '{ print $2 }'`                                                            2>&1 >>$logfile
+	if [ -z "$CS_PID" ]
+	then
+    echo "Process not found, no need to kill it"                                                                                                      2>&1 >>$logfile
+  else
+    echo "Process ID $CS_PID found, killing it"                                                                                                       2>&1 >>$logfile
+    kill -15 $CS_PID                                                                                                                                  2>&1 >>$logfile
+  fi
   echo "Try to start KNXd Control Daemon"                                                                                                             2>&1 >>$logfile
   REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/server_control.pl                                                                2>&1 >>$logfile &
+  if [ $? -eq 0 ]
+  then
+    echo "KNXd Control Daemon restart successfully completed."                                                                                        2>&1 >>$logfile
+  else
+    echo "KNXd Control Daemon cannot be started. That's bad. Check the logfile!"                                                                      2>&1 >>$logfile
+  fi
   echo "Try to restart KNXd"                                                                                                                          2>&1 >>$logfile
   service knxd stop                                                                                                                                   2>&1 >>$logfile
   service knxd start                                                                                                                                  2>&1 >>$logfile
