Installation w/o compilation - just install packages
Installation dauerte einfach zu lange.

diff --git a/daemon/daemon b/daemon/daemon
--- a/daemon/daemon
+++ b/daemon/daemon
@@ -16,8 +16,8 @@ PATH=$PATH.":REPLACEBYBASEFOLDER/sbin"
 
 ### END INIT INFO
 
-# Version 0.1
-# 28.10.2016 16:25:00
+# Version 1.3
+# 31.10.2016 22:10:57
 
 logfile=REPLACEBYBASEFOLDER/log/plugins/REPLACEBYSUBFOLDER/knxd.log
 flagfile=REPLACEBYBASEFOLDER/config/plugins/REPLACEBYSUBFOLDER/modify.me
@@ -31,30 +31,25 @@ then
   echo "modify.me found. Installing KNXd Plugin."
   echo "modify.me found. Installing."                                                                                                                 2>&1 >>$logfile
   cd REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/                                                                                             2>&1 >>$logfile
-  mkdir temp_install                                                                                                                                  2>&1 >>$logfile
-  tar -xvf REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/pthsem_*.tar.gz -C temp_install                                                        2>&1 >>$logfile
-  tar -xvf REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/knxd*.tar.gz    -C temp_install                                                        2>&1 >>$logfile
-  cd temp_install                                                                                                                                     2>&1 >>$logfile
-  chown loxberry:loxberry -R REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/                                                                     2>&1 >>$logfile
-  cd pthsem-*                                                                                                                                         2>&1 >>$logfile
-  dpkg-buildpackage -b -uc                                                                                                                            2>&1 >>$logfile
-  cd ..                                                                                                                                               2>&1 >>$logfile
   dpkg -i libpthsem*.deb                                                                                                                              2>&1 >>$logfile
-  cd knxd*                                                                                                                                            2>&1 >>$logfile
-  dpkg-buildpackage -b -uc                                                                                                                            2>&1 >>$logfile
-  cd ..                                                                                                                                               2>&1 >>$logfile
   dpkg -i knxd_*.deb knxd-tools_*.deb                                                                                                                 2>&1 >>$logfile
-  cd REPLACEBYBASEFOLDER/data/plugins/REPLACEBYSUBFOLDER/                                                                                             2>&1 >>$logfile
-  rm -rf temp_install                                                                                                                                 2>&1 >>$logfile
   KNXD_OPTS="`grep KNXD_OPTS $configfile`"                                                                                                            2>&1 >>$logfile
   echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
   sed -i  "s%KNXD_OPTS=.*%$KNXD_OPTS%g" $INPUTFILE                                                                                                    2>&1 >>$logfile
   ln -s REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/eibtime.pl REPLACEBYBASEFOLDER2/system/cron/cron.01min/REPLACEBYPLUGINNAME 2>&1 >>$logfile
   echo "Try to start KNXd Control Daemon"                                                                                                             2>&1 >>$logfile
   REPLACEBYBASEFOLDER/webfrontend/cgi/plugins/REPLACEBYSUBFOLDER/bin/server_control.pl                                                                2>&1 >>$logfile &
+  if [ $? -eq 0 ]
+  then
+    echo "KNXd Control Daemon successfully started"                                                                                                   2>&1 >>$logfile
+  else
+    echo "KNXd Control Daemon start failed"                                                                                                           2>&1 >>$logfile
+  fi
+  echo "Try to read KNXd Version"                                                                                                                     2>&1 >>$logfile
   /usr/bin/knxd -V                                                                                                                                    2>&1 >>$logfile
   if [ $? -eq 0 ]
   then
+    echo "KNXd Version successfully read"                                                                                                             2>&1 >>$logfile
     echo "Removing $flagfile"                                                                                                                         2>&1 >>$logfile
     rm $flagfile                                                                                                                                      2>&1 >>$logfile
     echo "Try to restart KNXd"                                                                                                                        2>&1 >>$logfile
@@ -62,12 +57,16 @@ then
     service knxd start                                                                                                                                2>&1 >>$logfile
     if [ $? -eq 0 ]
     then
-      echo "Installation successfully completed."                                                                                                     2>&1 >>$logfile
+      echo "KNXd successfully restarted."                                                                                                             2>&1 >>$logfile
+      echo "Installation complete."                                                                                                                   2>&1 >>$logfile
       exit 0
+    else
+      echo "KNXd cannot be started. That's bad."                                                                                                      2>&1 >>$logfile
     fi
+  else
+    echo "KNXd Version cannot be read. That's bad."                                                                                                   2>&1 >>$logfile
   fi
 else
-  echo "Plugin modification already done."
   echo "Plugin modification already done."                                                                                                            2>&1 >>$logfile
   KNXD_OPTS="`grep KNXD_OPTS $configfile`"
   echo "Configure KNXd to use $KNXD_OPTS"                                                                                                             2>&1 >>$logfile
@@ -79,11 +78,13 @@ else
   service knxd start                                                                                                                                  2>&1 >>$logfile
   if [ $? -eq 0 ]
   then
-    echo "Installation successfully completed."                                                                                                       2>&1 >>$logfile
+    echo "Restart successfully completed."                                                                                                            2>&1 >>$logfile
     exit 0
+  else
+    echo "KNXd cannot be started. That's bad."                                                                                                        2>&1 >>$logfile
   fi
 fi
 
 # When arriving here, something goes wrong
-echo "Installation completed with problems."                                                                                                          2>&1 >>$logfile
+echo "Oh oh, I had problems. Please read the Plugin-Logfile for details."                                                                             2>&1 >>$logfile
 exit 1
